name: Expo Publish and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-and-test:
    name: Install, publish, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Publish to Expo
        if: success() && github.event_name == 'push'
        run: expo publish --non-interactive
