name: Test, Lint, and Type Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint-typecheck:
    name: Run tests, linting, and type checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn jest --no-cache --testMatch='**/__tests__/**/*.test.[jt]s?(x)'

      - name: Run linting
        run: yarn lint

      - name: Run type checking
        run: yarn typecheck
